// Generated by CoffeeScript 2.6.1
var sequelize;

sequelize = require("sequelize");

module.exports = {
  method: "get",
  path: "/api/auth/valid",
  handler: async function(req, h) {
    var auth, db, err, user;
    auth = req.auth.credentials;
    db = req.server.db;
    try {
      user = (await db.icat_users_extend.findOne({
        attributes: {
          exclude: ["dzUid", "salt", "createdAt", "updatedAt"]
        },
        where: {
          uid: auth.uid
        },
        //order:[[db.icat_credits_calc,"creditCalcid","desc"]]
        include: [
          {
            model: db.icat_goods,
            include: [
              {
                model: db.icat_credits
              }
            ]
          },
          {
            /*应该暂时没用了，因为有api_my
            {
              model: db.icat_credits_calc
              #不知道为什么无法正常排序
              attributes:["creditCalcid","creditid","uid","user","creditName","calc","action","freeze","payPlatform","timestamp"]
              #order:[["timestamp","ASC"]]
            }
             */
            model: db.icat_vars
          }
        ]
      }));
      return {
        ok: true,
        msg: "验证成功",
        data: user
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
